### ISSUE TITLE
Give uuid back to user upon creation

### ISSUE THREAD

**Issue by Shurlow** [wkentdag/sup#14]
When a new user is created from client, they have no way of knowing their uuid (which is needed for getting visible status, friends etc).

**Comment by Shurlow** [comment]
Perhaps we should just create the uuid on the client instead?

**Comment by wkentdag** [comment]
The UID is set by postgres so I don't think we should set it ourselves. It's pretty easy to change the route to just return the new UID, i'lll set it up tonight
