### ISSUE TITLE
Posting a SUP

### ISSUE THREAD

**Issue by Shurlow** [wkentdag/sup#18]
Can we merge what `/status/:id/viewers` [here](https://github.com/wkentdag/sup/blob/3e41636d9e2f44e6f8bccc599256cdcb11a7cef4/routes/status.js#L182) does into the `/status` [post](https://github.com/wkentdag/sup/blob/3e41636d9e2f44e6f8bccc599256cdcb11a7cef4/routes/status.js#L46) route?

Make it take an array of user_id's to add tot he statusView table as opposed to just one user.

**Comment by wkentdag** [comment]
I was wondering if we should do that too. Think it was good to keep them separate as we built up the API but now it would make sense to have it all wrapped together
